name: Go

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.3"
        continue-on-error: true

      - name: Build for ${{ matrix.os }} and ${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o ./build/${{ matrix.os }}_${{ matrix.arch }}/myapp

      - name: Upload build artifacts to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/*
        env:
          GITHUB_TOKEN: ${{ secrets.BHCT_TOKEN }}
